### ISSUE TITLE
Default missed at least when in "discriminator"

### ISSUE THREAD

**Issue by mohawk2** [mojolicious/json-validator#106]
From this: https://metacpan.org/source/JHTHORSEN/JSON-Validator-2.05/t/openapi.t#L66-67

```perl
# ...
        huntingSkill => {
          default => 'lazy',
          enum    => ['clueless', 'lazy', 'adventurous', 'aggressive'],
          type    => 'string',
        }
# ...
@errors = $openapi->validate_input({petType => 'Cat'}, $schema);
is "@errors", "/huntingSkill: Missing property.", "missing property";
```

Why is the `huntingSkill` considered "missing" when there is a default given?

**Comment by jhthorsen** [comment]
I don't think there's anything handling "default" values. Please see #55 for the full discussion.

**Comment by mohawk2** [comment]
You're right. This is a bit of a nightmare. If you'd like to close this, please do ;-)

**Comment by plk** [comment]
I might look at a PR for this as defaults are extremely useful. We use them a lot. The discussion seemed to be around naming and where to implement and didn't seem particularly complex. Are there some reasons why nobody touched this? Are there some aspects which are difficult to implement?

**Comment by jhthorsen** [comment]
I'm closing this in favour of #155. Please have a look @plk.
