### ISSUE TITLE
adding error code to JSON::Validator::Error

### ISSUE THREAD

**Issue by beyondcreed** [mojolicious/json-validator#129]
just curious if it would be possible to add error_code to JSON::Validator::Error

e.g.

```
use JSON::Validator::Error;
my $err = JSON::Validator::Error->new($path, $message, $error_code);
```
use case for this would be to localize on front-end the message based on specific error code returned by API, could likely use message to stuff the code, but thought it would be cleaner to keep it separate.

**Comment by beyondcreed** [comment]
sure, I'll head over there

**Comment by jhthorsen** [comment]
How would the error code help you? Can you give me some examples of what they might be and how you would use them?

**Comment by beyondcreed** [comment]
I commented on #130 with sample use case. you can check there.

**Comment by jhthorsen** [comment]
Could you also have a look at https://github.com/mojolicious/json-validator/pull/133 to see what you think about that PR?
