### ISSUE TITLE
How handle string OR null value ?

### ISSUE THREAD

**Issue by pamasse** [mojolicious/json-validator#136]
Hi, 

I'm trying to accept string value validate with a regex and also, `null` (undef) value.
For example:
"nameservers": [{
    	"ns": "ns1.nic.fr",
    	"ip": null
    }]
And 
"nameservers": [{
    	"ns": "ns1.nic.fr",
    	"ip": "1.1.1.1"
    }]
must be accepted.

I don't see any solution with the actual version of joi.
Have you any idea to achieve this ?

Thx

**Comment by jhthorsen** [comment]
Thanks for the issue 👍

This should be fixed in the upcoming version.
