### ISSUE TITLE
JSON::Validator::OpenAPI - can't see good alternative

### ISSUE THREAD

**Issue by mohawk2** [mojolicious/json-validator#145]
* JSON::Validator version: 3+
* Perl version: NA
* Operating system: NA

Previously to JV 3, there was available `JSON::Validator::OpenAPI`. Now it's been deleted. `Mojolicious::Plugin::OpenAPI` has `JSON::Validator::OpenAPI::Mojolicious`, which blandly says "use `Mojolicious::Plugin::OpenAPI`, not this directly".

Previously, various not-directly-Mojo libraries were using `JSON::Validator::OpenAPI`, to encapsulate an actual OpenAPI spec, not just a generic JSON Schema spec.

It seems that there is now not a way to encapsulate an actual OpenAPI spec. Can you update the docs to show how to do that post this change? Or even restore `JSON::Validator::OpenAPI`. Given those libraries aren't Mojo, there is no obvious way to use `Mojolicious::Plugin::OpenAPI` to replace this capability.

**Comment by jhthorsen** [comment]
I doubt this will be fixed, since I don't really want to mix OpenAPI with JSON::Validator.

What do you mean with "Previously, various not-directly-Mojo libraries were using"? Which libraries is that?

**Comment by mohawk2** [comment]
The three that I linked to this issue, for a start.

**Comment by jhthorsen** [comment]
I don't see any reason for those two projects to use JSON::Validator::OpenAPI::Mojolicious instead of JSON::Validator.

**Comment by mohawk2** [comment]
For the same reason that this is not a blank page: https://metacpan.org/pod/release/JHTHORSEN/JSON-Validator-2.19/lib/JSON/Validator/OpenAPI.pm

That an OpenAPI spec has slightly different requirements from other types of JSON Schema.

**Comment by jhthorsen** [comment]
I’m going to close this issue unless you can actually tell me why you can’t use JSON::Validator.
