### ISSUE TITLE
can't validate an empty schema with `coerce=>'defaults'`

### ISSUE THREAD

**Issue by karenetheridge** [mojolicious/json-validator#158]
This script:

    use strict;
    use warnings;
    use JSON::Validator;
    my $schema = {
        '$schema' => 'http://json-schema.org/draft-07/schema#',
    };

    my $validator = JSON::Validator->new(coerce => 'defaults');
    $validator->load_and_validate_schema($schema, { schema => 'http://json-schema.org/draft-07/schema#' });

gives:

    Not a HASH reference at /Users/ether/.perlbrew/libs/26.3@std/lib/perl5/JSON/Validator.pm line 929.

Inspecting the stack trace, it looks like it cannot parse the part of the schema spec that says `default=>true` for the `object` definition?  `$r` is supposed to be a hashref on line 929 but instead it is just a `JSON::PP::true`.

This is with JSON::Validator 3.11 on perl 5.26.3, darwin (OSX).

**Comment by jhthorsen** [comment]
This is indeed a bug. And unfortunately, I don't know how to fix it. Last time I encountered this case, I added a quick fix/hack:

https://github.com/mojolicious/json-validator/blob/8c822f2fca67e5208def6b081a943ab6308d5601/lib/JSON/Validator.pm#L571

I'm not proud of that line, but that's unfortunately how it is now... I think if anyone provides a fix for this issue, then L571 and L572 can be removed as well.

**Comment by jhthorsen** [comment]
I'm closing this issue, since there does not seem to better fix available.

**Comment by karenetheridge** [comment]
Is there harm in leaving it open? I've been trying to find time to work on it, as I'll need this feature for an upcoming project. :(

**Comment by jhthorsen** [comment]
I'll reopen the issue if you let me know what's wrong with the fix.

**Comment by karenetheridge** [comment]
I don't understand -- what fix are you referring to?

**Comment by karenetheridge** [comment]
please reopen this -- it is still a problem.
