### ISSUE TITLE
unsupported keywords for numeric types: exclusiveMaximum, exclusiveMinimum

### ISSUE THREAD

**Issue by karenetheridge** [mojolicious/json-validator#191]
described here:
https://json-schema.org/understanding-json-schema/reference/numeric.html?highlight=exclusivemaximum  
https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-6.2.3

**Comment by jhthorsen** [comment]
Isn't that tested here? https://github.com/mojolicious/json-validator/blob/master/t/jv-number.t#L37

**Comment by karenetheridge** [comment]
apologies! I read the grep wrong! no excuses. :(

```
lib/JSON/Validator.pm:648:  my $cmp_with = $schema->{exclusiveMaximum} // '';
lib/JSON/Validator.pm:672:  my $cmp_with = $schema->{exclusiveMinimum} // '';
```

**Comment by jhthorsen** [comment]
No worries. Glad I didn't misunderstand 😄
