### ISSUE TITLE
$args variable is missed in the definition of "openapi.valid_input"

### ISSUE THREAD

**Issue by KalessinD** [mojolicious/json-validator#219]
* JSON::Validator version: 3.33
* Perl version: 5.26.3
* Operating system: Cent Os

### Steps to reproduce the behavior

There exists the defenition of "openapi.valid_input" helper in Mojolicious::Plugin::OpenAPI package.
Here it is:

$app->helper('openapi.valid_input' => sub { _helper_validate($_[0]) ? undef : $_[0] });

I suppose that the $_[1] argument was omitted in the call of "_helper_validate" method.
That's why impossible to pass "$args" variable into this method.

The proper version of this line should look as follows:

$app->helper('openapi.valid_input' => sub { _helper_validate($_[0], $_[1]) ? undef : $_[0] });

Please fix it.

### Expected behavior
EXPLAIN WHAT SHOULD HAPPEN HERE
I expect that "$args" must be passed into "_helper_validate" method

### Actual behavior
EXPLAIN WHAT HAPPENED INSTEAD HERE
Right now the "$args" variable can't reach "_helper_validate" method as it was expected.

**Comment by jhthorsen** [comment]
Seems like this issue is created for the wrong github project.
