### ISSUE TITLE
Migration path from JSON::Validator::joi

### ISSUE THREAD

**Issue by mattias-p** [mojolicious/json-validator#221]
* JSON::Validator version: 4.02
* Perl version: 5.26
* Operating system: CentOS 8

I've got a bunch of code using JSON::Validator::joi like this:
```perl
use JSON::Validator qw( joi );

sub api_key {
    return joi->string->regex('^[a-zA-Z0-9-_]{1,512}$');
}
```
When I run this code I get lots of deprecation warnings about this use of `joi`.
The documentation at https://metacpan.org/pod/JSON::Validator clearly marks the `joi` interface as deprecated.
So far, so good.
However, I can't find any documentation on intended migration paths away from the deprecated interface.
Also, https://metacpan.org/pod/JSON::Validator::Joi still prescribes the use of the deprecated interface.

**Comment by jhthorsen** [comment]
Oh. That's not very nice. I've just made a new release where you can do:

```
use JSON::Validator::Joi qw(joi);
```

The reason why JSON::Validator::joi() is deprecated is because it could also take `$data` which I found very clumsy.
