### ISSUE TITLE
OpenAPIv2 and v3 schema classes should have introspection methods

### ISSUE THREAD

**Issue by mohawk2** [mojolicious/json-validator#228]
Further to needs expressed in #227, one of the grant-proposal authors writes, and I also find this valuable re introspection:

> Personally I'd like to see methods that formalise the existence of things that would otherwise be hash lookups, e.g. parameters, paths, models, maybe `get_model_by_name`, stuff like that

Reproduced here at request of @jhthorsen after it was deleted from #227.

**Comment by jhthorsen** [comment]
This issue needs more details. What exactly is wanted? Please create a (partial) list of what you want to ask the schema of, and also a usecase for why that information is useful.

**Comment by jhthorsen** [comment]
Here are some ideas:

* Get all request and response parameters by HTTP method, path and status code. This is required for validation #227
* Get all paths and HTTP methods.
* Get operation(s) by operationId or tags. This is useful for libraries such as OpenAPI::Client
* Get the base URL. This is useful for libraries such as OpenAPI::Client

**Comment by jhthorsen** [comment]
Going to close this issue, since no more information has been provided. (I don't mind re-opening this though)
