### ISSUE TITLE
Incorrect behaviour when extra object properties present

### ISSUE THREAD

**Issue by DrHyde** [mojolicious/json-validator#240]
* JSON::Validator version: 4.13
* Perl version: 5.30.1
* Operating system: MacOS Catalina

### Steps to reproduce the behavior

Given a schema that specifies this object:

```json
    ...
    "location":   {
        "type": "object",
        "properties": {
            "postcode": { "type": "string" },
            "region": { "type": "string" },
            "country": { "type": "string" }
        }
    },
    ...
```

ie, which validates that `location` is an object and that the `postcode`, `region`, and `country` fields are optional strings, try to validate this JSON:

```json
    ...
    "location": {
        "postcode": "TN39 4AA",
        "region": "East Sussex",
        "country": "GB",
        "door_colour": "orange"
    },
    ...
```

### Expected behavior

No error, because I've not said `"additionalProperties": false`, and the default is supposed to be `true`.

### Actual behavior

Perl spits an error: `Can't call method "req" on an undefined value ...`

NB that if I explicitly set `"additionalProperties": true` then we get the same incorrect behaviour. If I set it to `false` then I get a sensible error.

**Comment by jhthorsen** [comment]
I don’t see how “Can't call method "req" on an undefined value” is related to this. Also the schema does not reflect the error description.

Please provide a failing test. You can use

**Comment by DrHyde** [comment]
Hmmm, I may have cast blame incorrectly as I can't see how that error can possibly be generated. There's definitely *something* funky going on with additionalProperties, but I'll close the ticket for now and open another if I can boil it down to a small example.
